AdaloHQ/material-components-library

package.json
yarn.lock

Currently, there is an issue with the latest version of the CLI (having to do with its dependencies) that is causing icons to break on the material components library.
List the old version of the cli in the `package.json`, and use `yarn link` locally to publish.
This isn't the greatest solution, but it's a good workaround for now.

downgraded cli to get icons working

---

package.json

I already published with this changed to Adalo, but we obviously should have github reflect the correct version number.

bump version to 0.0.42

---

package.json
src/TextButton/TextButton.js

After the horizontal card list got published, there was a weird issue with the margins on the text buttons.
Add a margin on the text when there's an icon.
I don't really know what went wrong, but this does work so....

Adds margin on button text

---

package.json
src/HorizontalImageList/ImageScrollView.js
src/HorizontalImageList/index.js

weird spacing was occurring between the bottom bar and the image each item in the horizontal card list. This was happening when there were multiple lines of text in at least one of the imageItem's titles on the card. 
The flex style property was causing the view surrounding the bottom bar to fill space that it didn't need to fill causing the weird spacing, so I removed the flex prop and it looks like that fixed it.

deleted style prop to fix bug

---

package.json
src/Icon/index.js

When an action is added to an `icon` component, the height and width is doubled
Instead of doubling the height and width, we continue using the icon's height and width and center with flex.

🐞 Icon’s padding depends on whether an action is set or not

---

README.md
package.json
src/TextButton/TextButton.js

Buttons inside list keep start spinning on the first click and you have to click a second time to make it work. In addition to that, they return an error message in the first click.
add treatment when there is no action attached to the button.

Fix spinning when there is no action attached to button

---

package.json
src/IconToggle/index.js

Currently, the `IconToggle` component does not eager update. So, when updates are slow, the component looks incredibly slow.
Implement eager updates. Use a queue to keep track of local changes, and if there are local changes, refer to the latest change.
When props are updated, the array will knock off the front value in the queue.
There is a bugfix inside runner that will need to be merged in before these changes are made live.
I also refactored the component to be a functional component while I was at it, should be some good code cleanup...
https://github.com/AdaloHQ/runner/pull/288

Eager Update for IconToggle

---

package.json
src/IconToggle/index.js

This code is already live, just hasn't been merged in yet.
This implements a hotfix to the eager updates so that values can be undefined and still changed. In certain DBs, especially external collections, `undefined` is used instead of `false` at times.

Toggle Eager Update Hotfix

---

package.json
src/IconToggle/index.js

`IconToggle` breaks the rules of hooks as we have multiple instances of `react` loaded
Refactoring back to a class component doesn't trigger this error. Not the long term solution at all, but gets us out of the hole for moving TS and Context forward.
https://github.com/AdaloHQ/runner/pull/365

Refactor `IconToggle` back to class Component

---

package.json
src/SimpleList/index.js

As part of the empty state changes, Andy accidentally introduced an obscure bug where old simple lists without a background object were crashing.
He was trying to access the object outside the if block that checks that it exists.
Use `|| {}` to prevent the crash.
This is so small that once someone approves I want to make it live immediately.

Fixes crashing for simple list

---

package.json
src/ImageList/index.js

The overlay for the text seems to wayyyy larger (height) than it previously was and takes up the majority of the image.
We remove the `min-height` property that was setted to `100px` and causing the behavior.

Image list text background overlay using fixed height

---

package.json
src/HorizontalImageList/ImageItem.js
src/ImageList/index.js

Megan's app (https://app.adalo.com/apps/e788c50c-981a-43db-84ad-44251011f079/screens) was crashing when you tried to search the image list, due to `title` or `subtitle` being undefined.
Check if they are defined before accessing its value.
I was seeing another error in the console having to do with a similar issue in HorizontalImageList so I went ahead and cleaned that up too.
Also, the code is already live on production, I wanted to ship out the fix asap because apps were crashing.

Checks if title and subtitle are defined before filtering

---

package.json
src/AvatarList/ImageScrollView.pwa.js
src/AvatarList/index.js
src/ChipList/ImageScrollView.js
src/ChipList/ImageScrollView.pwa.js
src/ChipList/ImageScrollView.web.js
src/ChipList/index.js
src/HorizontalImageList/ImageScrollView.pwa.js
src/HorizontalImageList/ImageScrollView.web.js
src/HorizontalImageList/index.js

Currently on PWA, it's impossible to scroll vertically when you start the scroll on a horizontal list. 
Turns out it's a bug with react-native-web. 
Followed a workaround [here](https://codesandbox.io/s/ywjqyoo3rz?file=/src/App.js), originally pulled from [here](https://github.com/necolas/react-native-web/issues/1042) to implement the fix for PWA specifically.
I also refactored ChipList and HorizontalImageList to reduce duplicated code in the process.
Once approved, we'll need to publish a new version of the library.

Vertical Scrolling on a Horizontal List

---

package.json
scripts/install.sh
yarn.lock

On 11/30/21, all iOS builds started failing during the bundle resources step. This version fixes the issues.
From slack:
> Babel, either on material-components-library or the cli (not sure which), was really outdated and wasn't interfacing properly with typescript. So we think that was the issue.
> The other potential issue was that we had an install script that was adding the latest version of react-native-paper to the root level template-app, which was done out of an abundance of caution but isn't necessary so I removed that too
Check out this thread for more info: https://foundryplatform.slack.com/archives/C01C93SGL1Z/p1638273514162600

Fix for outage

---

package.json
src/SimpleList/index.js
src/SimpleList/manifest.json

Makers cannot add actions to the left section icon/image/avatar of simple lists but they can for the right section.
Adds the ability to add actions to left section of simple list. **This PR contrasts with related PR [here](https://github.com/AdaloHQ/material-components-library/pull/91) because the icon link has an animation that matches the right section icon.**
After:
- Link to [Trello](https://trello.com/c/WSahrS46/106-add-actions-to-the-left-section-of-a-simple-list)

Add Actions to the Left Section of a Simple List (with icon animation)

---

package.json
src/SimpleList/index.js

Simple list `justifyContent: 'flex-center';` is breaking an app as this value doesn't exists for react-native.
Changed `flex-center` to `center`.
https://reactnative.dev/docs/flexbox#justify-content

Fix simple list justifyContent value breaking app

---

package.json
src/SimpleList/index.js

Problem:
Native builds would crash when rendering a simple list with a click action on the left item, because 'unset' is not a defined value for `pointerEvents` in React Native.
Solution:
Change the `pointerEvents` value to 'auto' when there is an action.

Change simple list pointer event to 'auto'

---

package.json
src/ActionButton/ActionButton.js
src/AppBar/AppBar.js
src/Icon/index.js

We want to show loading spinners for buttons. We currently only have a loading state for a regular button. This PR adds loading states for:
- Action Buttons
- Icon Buttons
- Icons Buttons inside the App Bar
We will not have loading states for Icon Toggles or Toggle-type Icon Buttons inside the App Bar.
This leaves only Icon Buttons inside the Tab Bar component, which will be dealt with separately.

Show loading spinners for action buttons, icons, and icons inside app bars

---

package.json
src/TabNavigator/index.js
yarn.lock

We want loading states for the bottom Tab Nav component. This passes in a new prop `showLoadingState`, which was implemented in https://github.com/AdaloHQ/react-native-material-ui/pull/1. It also makes `handleChangeTab` an async function, which is awaited in `react-native-material-ui`.

Pass in a loading state to bottom navigation component

---

package.json
scripts/install.sh

Android builds are failing with version 4.1.0 of @react-native-community/blur. This fixes this dependency to version 4.0.0

Fix react-native-community/blur to 4.0.0

---

package.json
src/AppBar/AppBar.js
src/AppBar/blur.android.js
src/AppBar/blur.ios.js
src/AppBar/blur.web.js
yarn.lock

**Problem**
iOS devices with dynamic islands have a top margin showing on apps
[Adalo Forum - iPhone 14 Pro layout issue](https://forum.adalo.com/t/iphone-14-pro-layout-issue/31977/11)
**Solution**
Patch AppBar margins for devices with dynamic island and notch
**Tests to check for bug fix**
**Test to check for regressions**
**Screenshots**
Before fix
iPhone 14 Pro Max, AppBar with top margin
iPhone 14, AppBar with top margin
iPhone 14 Pro Max AppBar & BottomSheet, AppBar with top margin, no issues on BottomSheet
After fix
iPhone 14 Pro Max AppBar after fix
iPhone 14 Pro Max no AppBar & content below dynamic island after fix
iPhone 14 AppBar after fix
iPhone SE no regressions after fix
iPhone 14 Pro Max AppBar & BottomSheet, no regressions on BottomSheet

Fix dynamic island top padding

---

package.json
src/ImageList/index.js

From this slack thread: https://foundryplatform.slack.com/archives/C040NBFNLKW/p1686228400008559
After the last release of `material-components-library`, image lists started crashing with an error related to the `RippleFeedback` component not supporting `null` as a children.
Replace the `null` with a `React.Fragment` to stop `RippleFeedback` from crashing.

Fix ripple null children crash

---

package.json
src/lib/utils.js

Images appear blurry or generally of lower quality since the image performance updates.
Load images from Imgix with a minimum device pixel ratio of 2x, e.g. given an Image component size of 100x100, load at least a 200x200 image to fill the space.
https://foundryplatform.slack.com/archives/CL8DWS6JJ/p1686533274300919
- Runner, equivalent change: https://github.com/AdaloHQ/runner/pull/738

fix: ensure minimum of 2x device pixel ratio to help with blur

---

package.json
src/lib/utils.js

Makers cannot use their own imgix props anymore by attaching them to the URL.
Keep imgix props passed in through the URL.

Keep imgix props

---

adalo.json
package.json
scripts/install.sh
yarn.lock

The package `react-native-linear-gradient` published a change that turned out to break Android builds.
We weren't specifying a version when installing this dependency that meant this latest version was automatically picked up during the build process, causing builds to fail.
Note, it's not clear whether this version is an "official" breaking change or merely one that our Material Components wasn't compatible with.
The fix was to specify the version before the breaking version.
Relates to this service interruption: https://www.notion.so/2023-07-23-Android-build-failures-91230bc72fde4ddbb2bc44b2acca0c91

fix: lock dependencies and move from scripts to package.json

---

package.json
src/TabNavigator/index.js

Reverts AdaloHQ/material-components-library#125
This is no longer needed since we're now using layout guides for the Responsive Previewer

Revert "Tweak/bottom nav size on responsive previewer"

---

package.json
src/ImageList/index.js

When the Image List component loads, the columns wrap.  E.g. if you selected 2 columns, it would render 1, 3 columns would render 2 and so on.
We listen for an On Layout event to fire, enabling the component width to be set correctly, ensuring the image "cells" or columns are the correct width.
When the component first loads, the layout event does not fire.  On subsequent visits to the screen, the layout event fires and the component loads correctly (perhaps where the screen isn't rendered in the foreground?)
We briefly render a loading state which did not have a listener for layout events.   Adding the `onLayout` event to this loading state correctly sets the width of the component allowing the image "cells" to render at the correct width.
Published `0.9.49` for testing.

Fix: Image List column rendering

---

package.json
src/SimpleList/index.js

Simple List, when configured to have 2 lines for subtitle causes it to break out of its bounds.
The component relies on onLayout to get the component width that won't fire with the SSR technique we use to render the component for the bounds calculation.  When displaying the component within Builder, we pass some extra metadata props to the component, one of which is `_width` that we can use as a fallback.

Fix: Simple List subtitle effect on editor bounds

---

package.json
src/TextButton/TextButton.js
src/TextButton/textButtonManifest.json

We want to be able to resize buttons vertically and create some preset options for variable icon and text sizing.
Set `resizeY` to true and added dropdown for "Text & Icon Sizing". If we don't have a value set for `sizing`, we use the old styling for the text and icon. If we do have a value for `sizing`, we use our new preset styles. Also, shadow is now off by default.
https://github.com/AdaloHQ/material-components-library/assets/46685700/bb7a3389-2279-4030-a1db-075bb97d3a40

Expanded button resizing

---

package.json
src/TextButton/textButtonManifest.json

We want the dropdowns to be in the new "Edit Styles" menu.
Set the `style` prop for both dropdowns.

Add button dropdowns to edit styles

---

package.json
src/Shared/EmptyState.js

When there's no Empty State image, there is no gap between text elements and the button element.
Ensure when there's no button, that a margin is applied to create a gap between the text elements and the button element.
Note; when there's an Image specified, that some extra margin is applied to the top and bottom of the Empty State component.  When there's no image, there's no extra margin applied.  This is existing behaviour that I opted to leave as-is to avoid creating unexpected gaps in maker's layouts.
This also fixes a secondary issue where the image wasn't showing in Builder.

Fix: List Empty States

---

package.json
yarn.lock

Published for testing as version 0.9.64: https://app.adalo.com/admin/marketplace/@protonapp/material-components

Maintenance: upgrade react-native-device-info

---

package.json
src/ActionButton/ActionButton.js
src/ActionButton/manifest.json
src/AppBar/AppBar.js
src/AppBar/manifest.json
src/AvatarList/index.js
src/AvatarList/manifest.json
src/CardList/index.js
src/CardList/manifest.json
src/ChipList/index.js
src/ChipList/manifest.json
src/HorizontalImageList/index.js
src/HorizontalImageList/manifest.json
src/Icon/index.js
src/Icon/manifest.json
src/IconToggle/manifest.json
src/ImageList/index.js
src/ImageList/manifest.json
src/SimpleList/index.js
src/SimpleList/manifest.json
src/TabNavigator/index.js
src/TabNavigator/manifest.json
src/TextButton/textButtonManifest.json
yarn.lock

We want to add custom icons
Add support for custom icons by updating the library that handles icons and updating manifest to indicate custom icons are supported.
https://github.com/AdaloHQ/packager/pull/531
https://github.com/AdaloHQ/backend/pull/1501
https://github.com/AdaloHQ/frontend/pull/3075
https://github.com/AdaloHQ/star-rating-component/pull/3
https://github.com/AdaloHQ/react-native-material-ui/pull/3
https://github.com/AdaloHQ/runner/pull/991
https://github.com/AdaloHQ/stopwatch/pull/38

Add custom icons to material components library
